export const Aragua = [
  {
    id: 1,
    ciudad: "Maracay",
    urbanizaciones: [
      "Calicanto",
      "El Centro",
      "El Hipódromo",
      "Fundación Mendoza",
      "La Barraca",
      "Piñonal",
      "San Jacinto",
      "José Félix Ribas",
      "La Soledad",
      "Caña de Azúcar",
    ],
    barrios: [
      "La Democracia",
      "San José",
      "23 de Enero",
      "La Cooperativa",
      "La Papelera",
      "Gonzalito",
      "San Vicente",
      "Santa Rosa",
    ],
  },
  { id: 2, ciudad: "Turmero" },
  { id: 3, ciudad: "El Limón" },
  { id: 4, ciudad: "Cagua" },
  { id: 5, ciudad: "La Victoria" },
  { id: 6, ciudad: "Villa de Cura" },
  { id: 7, ciudad: "Palo Negro" },
  { id: 8, ciudad: "Santa Rita" },
  { id: 9, ciudad: "San Mateo" },
  { id: 10, ciudad: "San Juan de los Morros" },
  { id: 11, ciudad: "Camatagua" },
  { id: 12, ciudad: "Colonia Tovar" },
  { id: 13, ciudad: "El Consejo" },
  { id: 14, ciudad: "Las Tejerías" },
  { id: 15, ciudad: "Ocumare de la Costa" },
  { id: 16, ciudad: "San Casimiro" },
  { id: 17, ciudad: "San Sebastián" },
  { id: 18, ciudad: "Santa Cruz" },
  { id: 19, ciudad: "Mariara" },
];
